# -----------------------------------------------------------
# 1. Istio Base (CRDs และ Config พื้นฐาน)
# -----------------------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: 1.24.1 # ใช้เวอร์ชันใหม่ที่เสถียร
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # แก้ปัญหา OutOfSync ที่ชอบกวนใจเวลามีการแก้ Webhook
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/0/failurePolicy

---
# -----------------------------------------------------------
# 2. Istiod (Control Plane - สมองของ Istio)
# -----------------------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.24.1
    helm:
      parameters:
        # บังคับลงที่ Master Node (Cloud) เพื่อความปลอดภัยและประสิทธิภาพ
        # ใช้ label มาตรฐานของ K3s: node-role.kubernetes.io/control-plane
        - name: global.nodeSelector.node-role\.kubernetes\.io/control-plane
          value: "true"
          forceString: true # สำคัญมาก! ต้องบังคับเป็น String ไม่งั้น ArgoCD จะ error
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/failurePolicy

---
# -----------------------------------------------------------
# 3. Istio Ingress Gateway (ประตูรับแขก - ตัวแทน Traefik)
# -----------------------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.24.1
    helm:
      parameters:
        # ตั้งชื่อให้ชัดเจน ArgoCD จะได้ไม่งง
        - name: fullnameOverride
          value: istio-ingress
        # เปิด LoadBalancer เพื่อดึง Port 80/443 ของเครื่องมาใช้ทันที
        - name: service.type
          value: LoadBalancer
        # บังคับให้ Gateway รันบน Master (Cloud) เท่านั้น
        - name: nodeSelector.node-role\.kubernetes\.io/control-plane
          value: "true"
          forceString: true
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true